name: Issue workflow

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  issue-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
