name: files

on: [workflow_dispatch]

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: filecreation
        run: |
          touch info.txt 
          echo "Hello" > info.txt
        
         
        
        
          
  
