name: files

on: [workflow_dispatch]

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: filecreation
        run: |
          touch info.txt 
          echo "Hello" > info.txt
      - name: backup
        run: |
          mkdir backup
          cp info.txt backup/
      - name: contents
        run: |
          echo "juurikansion sisältö"
          ls -la

          echo "backup sisältä"
          ls -la backup

          echo "info.txt sisältö"
          cat info.txt

          

     
        
         
        
        
          
  
