name: Push workflow

on:
  push:

env:
  APP_NAME: MathCounter
  APP_VERSION: v1.0.2

permissions:
  contents: write

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print app information
        run: |
          echo "Your app name is $APP_NAME and version is $APP_VERSION"

      - name: Add line to log
        run: |
          echo "${{vars.LOG_PREFIX}} Push implemented" >> log.txt
