name: Repo Info

on:
  workflow_dispatch:

jobs:
  repo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create commits.txt
        run: |
          touch commits.txt
