name: Repo Info

on:
  workflow_dispatch:

jobs:
  repo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create commits.txt
        run: |
          touch commits.txt

      - name: Add commit
        run: git log > commits.txt

      - name: Print commits.txt
        run: |
          cat commits.txt


      - name: Checkout tag 1.0
        uses: actions/checkout@v4
        with:
          ref: 1.0

      - name: Print README
        run: cat README.md
